"""settings

Revision ID: 767f8ae302cd
Revises: 68943f6a1ddb
Create Date: 2025-08-29 18:18:05.212819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767f8ae302cd'
down_revision = '68943f6a1ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_notif', sa.Boolean(), nullable=True),
    sa.Column('mobile_notif', sa.Boolean(), nullable=True),
    sa.Column('theme_mode', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
