"""Added source_id to sensor

Revision ID: ddaf7c1dfeef
Revises: 4344cca639d7
Create Date: 2025-08-25 18:29:03.384041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddaf7c1dfeef'
down_revision = '4344cca639d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['source_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
