"""empty message

Revision ID: f39ffa3bcb5b
Revises: 0e532c24d038
Create Date: 2025-08-19 18:55:24.023133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39ffa3bcb5b'
down_revision = '0e532c24d038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_validated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('address_line', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line')
        batch_op.drop_column('is_validated')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
