"""customer_order_id_removed

Revision ID: f3a004c43e6e
Revises: 767f8ae302cd
Create Date: 2025-08-31 21:29:40.796695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a004c43e6e'
down_revision = '767f8ae302cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_customer_order_id_key'), type_='unique')
        batch_op.drop_column('customer_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('orders_customer_order_id_key'), ['customer_order_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
